### ISSUE TITLE
Search & replace mistake broke Mac OS X detection

### ISSUE THREAD

**Issue by AlexanderWirthSAP** [flapdoodle-oss/de.flapdoodle.os#10]
In CommonOS the `osNameMatches("Mac OS X")` was accidentally renamed to `osNameMatches("Mac CommonOS X")` when the class was renamed from `OS` to `CommonOS`. So now the detection no longer works correctly.

See here: https://github.com/flapdoodle-oss/de.flapdoodle.os/commit/7fffb8e327e7e61054771fb406311e3b2078ce77#diff-20d305bceba4be2379acb25b7705e220d40fa2875a00cb65d228a2d116c48774R37

**Comment by michaelmosmann** [comment]
@AlexanderWirthSAP 
upps. will fix this

**Comment by michaelmosmann** [comment]
@AlexanderWirthSAP .. there is a new release which will be visible in maven central soon.. close if it works for you:)

**Comment by AlexanderWirthSAP** [comment]
@michaelmosmann Thank you, I can confirm that it works again.
