### ISSUE TITLE
Pom for 1.4.3 is missing in mavenCentral

### ISSUE THREAD

**Issue by ydylla** [flapdoodle-oss/de.flapdoodle.os#12]
Hi,
it looks like the pom file for 1.4.3 is missing in mavenCentral:
https://repo.maven.apache.org/maven2/de/flapdoodle/de.flapdoodle.os/1.4.3/de.flapdoodle.os-1.4.3.pom
returns 404 and also does not appear in the [listing](https://repo.maven.apache.org/maven2/de/flapdoodle/de.flapdoodle.os/1.4.3/). Only the signature exists:
https://repo.maven.apache.org/maven2/de/flapdoodle/de.flapdoodle.os/1.4.3/de.flapdoodle.os-1.4.3.pom.asc

Also do you have a timeline for when [de.flapdoodle.embed.mongo](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo) will be released with the fixes from 1.4.3? I want to use it with Mint 21.2 😄

**Comment by michaelmosmann** [comment]
@ydylla .. hmm.. did a new release 1.4.4 .. strange..

**Comment by michaelmosmann** [comment]
@ydylla there is also a new release for de.flapdoodle.embed.mongo ..

**Comment by ydylla** [comment]
@michaelmosmann Thank you very much for your fast help. Now everything works again ❤️
