### ISSUE TITLE
Cannot detect OS version for amzn2023

### ISSUE THREAD

**Issue by selimok** [flapdoodle-oss/de.flapdoodle.os#21]
Hi There,
I currently switched my build environment from Amazon Linux 2 to Amazon 2023.

The new Kernel name is : 6.1.97-104.177.amzn2023.aarch64

But the resolver cannot identify the OS Version 
` State(Distribution)=GenericFeatureAwareVersion{7.0.0}:Platform{operatingSystem=Linux, architecture=ARM_64, distribution=Amazon},`

 The same output on Amazon Linux 2: Where Kernel Name was: 5.10.219-208.866.amzn2.aarch64
`State(Distribution)=GenericFeatureAwareVersion{7.0.0}:Platform{operatingSystem=Linux, architecture=ARM_64, distribution=Amazon, version=AmazonLinux2},`

I think thus, embedded mongo cannot be loaded on the new environment and the build fails. 

BTW: Is there any workaround for this?

Thanks for your help.

**Comment by selimok** [comment]
I'm closing the issue, since I wasn't using the latest version of flapdoodle. I now switched to de.flapdoodle.embed.mongo.spring3x:4.16.1 and the detection works as expected. 
Sorry for inconvenience.

**Comment by michaelmosmann** [comment]
@selimok your welcome:)
