### ISSUE TITLE
Failure to detect CentOs version

### ISSUE THREAD

**Issue by petrkalivoda** [flapdoodle-oss/de.flapdoodle.os#4]
As far as I know, CentOs (at least in 6.x) doesn't use os-release file and has its own centos-release. However this file is in different format which leads to detection failure by `OsReleaseFiles.versionMatches`. 

Example of centos-release file on system where I've encountered the problem:
```
[root@localhost ~]# cat /etc/centos-release
CentOS release 6.10 (Final)
```

**Comment by michaelmosmann** [comment]
@petrkalivoda can you provide some debugging information? (see https://github.com/flapdoodle-oss/de.flapdoodle.os#run )

**Comment by michaelmosmann** [comment]
@petrkalivoda centos is now provided..
