### ISSUE TITLE
Linux Mint 21 is not detected

### ISSUE THREAD

**Issue by Andre0711er** [flapdoodle-oss/de.flapdoodle.os#5]
Linux Mint 21 is finally released. So code need to be updated. It's based on Ubuntu 22.04

Class: de.flapdoodle.os.linux.LinuxMintVersion
Changes: 

LINUX_MINT_21_0(UbuntuVersion.Ubuntu_22_04, OsReleaseFiles.osReleaseFileVersionIs("21"));

(Sorry, i'm not really firm how to pull it in repo)

**Comment by michaelmosmann** [comment]
@Andre0711er thanks.. will do it in the next days..

**Comment by michaelmosmann** [comment]
@Andre0711er did a new release , de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.4.9 should be in central in the next hours
